### ISSUE TITLE
Dockerfile instructions

### ISSUE THREAD

**Issue by tsak** [socheatsok78/unoserver-rest-api#3]
Thanks for making this API. It's working well and is surprisingly fast.

One thing I got a bit confused about with was changing the provided `Dockerfile` with the example from the README.

I got it all working with the following `Dockerfile`:

```Dockerfile
FROM libreofficedocker/libreoffice-unoserver:3.18

# The unoserver-rest-api version number
ARG UNOSERVER_REST_API_VERSION=0.7.0
ADD https://github.com/libreoffice-docker/unoserver-rest-api/releases/download/v${UNOSERVER_REST_API_VERSION}/s6-overlay-module.tar.zx /tmp
ADD https://github.com/libreoffice-docker/unoserver-rest-api/releases/download/v${UNOSERVER_REST_API_VERSION}/s6-overlay-module.tar.zx.sha256 /tmp
RUN cd /tmp && sha256sum -c *.sha256 && \
    tar -C / -Jxpf /tmp/s6-overlay-module.tar.zx && \
    rm -rf /tmp/*.tar*
EXPOSE 2004
```

```bash
docker build --tag unoserver-rest-api . && docker run --rm -p 2004:2004 unoserver-rest-api
```

## Changes

```diff
-FROM libreoffice-docker/libreoffice-unoserver:nightly
+FROM libreofficedocker/libreoffice-unoserver:3.18
```

`nightly` didn't work with version `0.7.0`. Also the Docker hub org name had an extraneous slash `-`.

Happy to create a PR with an update for the README.

**Comment by socheatsok78** [comment]
Hi, thank you for pointing out. 

Apologize for the naming. Unfortunately it already stuck with this weird naming thing due to Docker Hub organization name cannot contain `-`, lol. 

I'm working on overhauling the Docker image and the API. The `libreoffice-unoserver` already have the API built-it as for the new releases (previously it was not, you will have to manually build your own image but not anymore).

Also any form of contribution is welcome ;)

**Comment by socheatsok78** [comment]
It might be best to rename the GitHub organization to match Docker Hub. But Instead I've created a new organization `libreofficedocker`, now everything line up. But the [old organization](https://github.com/libreoffice-docker) will continue to exist.

This is a major decision since I do not have the number of people who will depend on this but it is better to migrate now.

Anyway still thank you for pointing out the obvious.
